const actionTypes = {
  SET_EVENTS_WITH_REPEAT: 'SET_EVENTS_WITH_REPEAT',
  SET_INFO_DAILY_EVENT: 'SET_INFO_DAILY_EVENT',
  UPDATE_CURRENT_TIME: 'UPDATE_CURRENT_TIME',
  SET_AUX_TIME: 'SET_AUX_TIME',
  UPDATE_AUX_TIME: 'UPDATE_AUX_TIME',
};

export default actionTypes;